services:
  _defaults:
    autowire: true
    autoconfigure: true

  HeimrichHannot\ContaoTeaserBundle\:
    resource: "../../{Migration}/*"

  HeimrichHannot\ContaoTeaserBundle\DataContainer\ContentListener:
    public: true

  HeimrichHannot\ContaoTeaserBundle\Command\MigrationCommand: ~