services:
  _defaults:
    autowire: true

# Listener

  huh.teaser.listener.hook:
    class: HeimrichHannot\ContaoTeaserBundle\EventListener\ContaoHooksListener
    public: true

  huh.teaser.listener.dc.content:
    class: HeimrichHannot\ContaoTeaserBundle\EventListener\DataContainer\ContentListener
    public: true