services:
  _defaults:
    autowire: true
    autoconfigure: true

  huh.teaser.listener.dc.content:
    class: HeimrichHannot\ContaoTeaserBundle\DataContainer\ContentListener
    public: true

  HeimrichHannot\ContaoTeaserBundle\Command\MigrationCommand: ~